# Generated by Django 5.1.2 on 2024-11-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='blee', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
